# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'openApps.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(992, 757)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.website_vertical_layout = QtWidgets.QVBoxLayout()
        self.website_vertical_layout.setObjectName("website_vertical_layout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.insert_website_button = QtWidgets.QPushButton(Form)
        self.insert_website_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.insert_website_button.setObjectName("insert_website_button")
        self.horizontalLayout.addWidget(self.insert_website_button)
        self.remove_website_button = QtWidgets.QPushButton(Form)
        self.remove_website_button.setObjectName("remove_website_button")
        self.horizontalLayout.addWidget(self.remove_website_button)
        self.run_website_button = QtWidgets.QPushButton(Form)
        self.run_website_button.setObjectName("run_website_button")
        self.horizontalLayout.addWidget(self.run_website_button)
        self.website_vertical_layout.addLayout(self.horizontalLayout)
        self.select_website_gridlayout = QtWidgets.QGridLayout()
        self.select_website_gridlayout.setObjectName("select_website_gridlayout")
        self.website_vertical_layout.addLayout(self.select_website_gridlayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.website_vertical_layout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.website_vertical_layout)
        self.desktop_vertical_layout = QtWidgets.QVBoxLayout()
        self.desktop_vertical_layout.setObjectName("desktop_vertical_layout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.insert_desktop_button = QtWidgets.QPushButton(Form)
        self.insert_desktop_button.setObjectName("insert_desktop_button")
        self.horizontalLayout_4.addWidget(self.insert_desktop_button)
        self.remove_desktop_button = QtWidgets.QPushButton(Form)
        self.remove_desktop_button.setObjectName("remove_desktop_button")
        self.horizontalLayout_4.addWidget(self.remove_desktop_button)
        self.run_desktop_button = QtWidgets.QPushButton(Form)
        self.run_desktop_button.setObjectName("run_desktop_button")
        self.horizontalLayout_4.addWidget(self.run_desktop_button)
        self.desktop_vertical_layout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.desktop_vertical_layout)
        self.select_desktop_gridlayout = QtWidgets.QGridLayout()
        self.select_desktop_gridlayout.setObjectName("select_desktop_gridlayout")
        self.verticalLayout_2.addLayout(self.select_desktop_gridlayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.run_all_button = QtWidgets.QPushButton(Form)
        self.run_all_button.setObjectName("run_all_button")
        self.horizontalLayout_3.addWidget(self.run_all_button)
        self.run_on_start_radio = QtWidgets.QRadioButton(Form)
        self.run_on_start_radio.setObjectName("run_on_start_radio")
        self.horizontalLayout_3.addWidget(self.run_on_start_radio)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.insert_website_button.setText(_translate("Form", "Insert Website"))
        self.remove_website_button.setText(_translate("Form", "Remove Website"))
        self.run_website_button.setText(_translate("Form", "Run"))
        self.insert_desktop_button.setText(_translate("Form", "Insert Desktop App"))
        self.remove_desktop_button.setText(_translate("Form", "Remove Desktop App"))
        self.run_desktop_button.setText(_translate("Form", "Run"))
        self.run_all_button.setText(_translate("Form", "Run All"))
        self.run_on_start_radio.setText(_translate("Form", "Run On Start Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
